server:
  port: 8088
  servlet:
    context-path: /Train

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/Train"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
